site_name: Titre de la documentation à remplacer
copyright: Texte apparaissant au bas des pages à remplacer
theme:
  name: material
  language: fr
  favicon: assets/favicon-32x32.png
  logo: assets/signature-PIV.svg
  font:
    text: "Open Sans"
    code: Roboto Mono
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.path
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
extra:
  generator: false
  homepage: index.html
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - offline
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
nav:
  - Accueil:
    - index.md
    - home/markdown-cheat-sheet.md
    - home/about.md
  - Section 1:
    - part1/page1.md
    - part1/page2.md
  - Section 2:
    - part2/page1.md
    - part2/page2.md